### PR TITLE
Replace ajv pack with standalone

### PR DESCRIPTION
**Pull request by dagda1**
following on from #6 , I have updated `ajv-json-loader` to use the latest ajv and replaced ajv-pack with ajv standalone.

I have also updated the code to typescript.  I needed to do this as I don't know ajv that well and the types kept me right.

All tests are passing but I had to update the snapshot code tests as the latest ajv code generates different code which is to be expected.

I would appreciate it if someone could cast a qualified eye over the new snapshots.

I do not know ajv very well at all so I would appreciate a more qualified look.

### CODE REVIEW

**Comment by downace** [comment]
Hi!

I've not used ajv and JSON schemas for a few years. Maybe someone of the ajv or ajv-pack collaborators may take a look.

Or I can just merge it and publish new version, so anyone can test it. It's new major release, so nothing should change for existing projects according to the semver.

**Comment by dagda1** [comment]
@downace i have just the project to try it on

**Comment by downace** [comment]
Done, the 0.2.0 version published at npmjs.com.

**Comment by dagda1** [comment]
> Done, the 0.2.0 version published at npmjs.com.

awesome, thank you, I'll follow up with another PR if there are any issues

**Pull request merged**
